apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-401523
  artifacts:
    # - image: us.gcr.io/ticketing-dev-401523/auth
    - image: alan1903/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '/src/**/*.ts'
            dest: .
    # - image: us.gcr.io/ticketing-dev-401523/client
    - image: alan1903/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    # - image: us.gcr.io/ticketing-dev-401523/tickets
    - image: alan1903/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '/src/**/*.ts'
            dest: .
    - image: alan1903/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '/src/**/*.ts'
            dest: .
    - image: alan1903/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: alan1903/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

